# Generated by Django 4.0.1 on 2022-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucommit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=15)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
